# Setup
title:        Kolt Ewing
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Kolt Ewing
  url:        http://koltclassic.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown